# POSTTEST 7 
## Nama : Alinda Azzahra
## NIM    : 2009106092

### Mengimport library

In [27]:
import tensorflow as tf

### Membuat variabel dari nilai random dengan shape 5,5

In [28]:
random_tensor = tf.random.normal([5,5])
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.26088262, -1.1665442 ,  0.55400825, -0.27793553, -0.24955325],
       [ 0.581209  , -0.6680276 , -0.14766154,  0.20139614, -0.8269629 ],
       [ 0.5781196 ,  0.8197328 , -0.8544065 ,  0.49225253,  0.6271775 ],
       [ 0.22934127, -0.9878349 ,  0.12698117,  0.15517129, -0.69218296],
       [ 0.5954512 ,  1.0592562 , -1.0577646 , -1.623136  ,  0.43469283]],
      dtype=float32)>

### Membuat variabel dari bilangan prima dengan shape 5,5

In [29]:
lists = [[2, 3, 5, 7, 11], 
              [13, 17, 19, 23, 29], 
              [31, 37, 41, 43, 47], 
              [53, 59, 61, 71, 73], 
              [79, 83, 89, 97, 101]]

prime_tensor = tf.convert_to_tensor(lists, dtype = tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)>

### Dimensi display dari random_tensor

In [72]:
print(random_tensor.shape)
print(random_tensor.get_shape())
print(tf.shape(random_tensor))

(5, 5)
(5, 5)
tf.Tensor([5 5], shape=(2,), dtype=int32)


### Dimensi display dari prime_tensor

In [73]:
print(prime_tensor.shape)
print(prime_tensor.get_shape())
print(tf.shape(prime_tensor))

(5, 5)
(5, 5)
tf.Tensor([5 5], shape=(2,), dtype=int32)


### Dimensi expansion dari random_tensor

In [70]:
expan1 = tf.expand_dims(random_tensor, axis=1)
print(expan1.shape)

(5, 1, 5)


### Dimensi expansion dari prime_tensor

In [71]:
expan2 = tf.expand_dims(prime_tensor, axis=2)
print(expan2.shape)

(5, 5, 1)


### Dimensi squeezing dari random_tensor

In [74]:
squeeze1 = tf.squeeze(random_tensor)
print(squeeze1.shape)

(5, 5)


### Dimensi squeezing dari prime_tensor

In [75]:
squeeze2 = tf.squeeze(prime_tensor)
print(squeeze2.shape)

(5, 5)


### Dimensi transpose dari random_tensor dan prime_tensor

In [76]:
trans1 = tf.transpose(random_tensor)
print(trans1.shape)

trans2 = tf.transpose(prime_tensor)
print(trans2.shape)

(5, 5)
(5, 5)


### Penjumlahan

In [77]:
tf.add(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  2.2608826,   1.8334558,   5.5540085,   6.7220645,  10.750446 ],
       [ 13.581209 ,  16.331972 ,  18.852339 ,  23.201397 ,  28.173037 ],
       [ 31.57812  ,  37.819733 ,  40.14559  ,  43.492252 ,  47.62718  ],
       [ 53.22934  ,  58.012165 ,  61.12698  ,  71.155174 ,  72.307816 ],
       [ 79.59545  ,  84.05926  ,  87.94224  ,  95.37686  , 101.43469  ]],
      dtype=float32)>

### Pengurangan

In [78]:
tf.subtract(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  -1.7391174,   -4.166544 ,   -4.4459915,   -7.2779355,
         -11.249554 ],
       [ -12.418791 ,  -17.668028 ,  -19.147661 ,  -22.798603 ,
         -29.826963 ],
       [ -30.42188  ,  -36.180267 ,  -41.85441  ,  -42.507748 ,
         -46.37282  ],
       [ -52.77066  ,  -59.987835 ,  -60.87302  ,  -70.844826 ,
         -73.692184 ],
       [ -78.40455  ,  -81.94074  ,  -90.05776  ,  -98.62314  ,
        -100.56531  ]], dtype=float32)>

### Perkalian

In [79]:
tf.multiply(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[   0.52176523,   -3.4996326 ,    2.7700412 ,   -1.9455488 ,
          -2.7450857 ],
       [   7.555717  ,  -11.356469  ,   -2.8055692 ,    4.632111  ,
         -23.981924  ],
       [  17.921707  ,   30.330112  ,  -35.030666  ,   21.166859  ,
          29.47734   ],
       [  12.155087  ,  -58.282257  ,    7.7458515 ,   11.017161  ,
         -50.529354  ],
       [  47.04064   ,   87.91827   ,  -94.14105   , -157.4442    ,
          43.903976  ]], dtype=float32)>

### Pembagian 

In [80]:
tf.divide(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.13044131, -0.38884807,  0.11080165, -0.03970508, -0.02268666],
       [ 0.04470839, -0.03929574, -0.00777166,  0.00875635, -0.02851596],
       [ 0.01864902,  0.02215494, -0.02083918,  0.01144773,  0.0133442 ],
       [ 0.00432719, -0.01674296,  0.00208166,  0.00218551, -0.00948196],
       [ 0.00753736,  0.01276212, -0.011885  , -0.01673336,  0.00430389]],
      dtype=float32)>

### Logaritma dari random_tensor

In [81]:
tf.math.log(random_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-1.3436847 ,         nan, -0.5905757 ,         nan,         nan],
       [-0.54264486,         nan,         nan, -1.6024815 ,         nan],
       [-0.5479746 , -0.19877686,         nan, -0.7087634 , -0.46652573],
       [-1.4725442 ,         nan, -2.0637164 , -1.8632257 ,         nan],
       [-0.5184359 ,  0.05756696,         nan,         nan, -0.83311564]],
      dtype=float32)>

### Logaritma dari prime_tensor

In [82]:
tf.math.log(prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.6931472, 1.0986123, 1.609438 , 1.9459102, 2.3978953],
       [2.5649493, 2.8332133, 2.944439 , 3.1354942, 3.3672957],
       [3.4339871, 3.610918 , 3.713572 , 3.7612002, 3.8501477],
       [3.9702919, 4.0775375, 4.1108737, 4.26268  , 4.2904596],
       [4.3694477, 4.4188404, 4.4886365, 4.574711 , 4.6151204]],
      dtype=float32)>

### Pangkat 

In [83]:
tf.pow(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 6.8059742e-02, -1.5874629e+00,  5.2189261e-02, -1.2811752e-04,
        -2.3377362e-07],
       [ 8.6361531e-04, -1.0507628e-03, -1.6446758e-16,  9.8441031e-17,
        -4.0466399e-03],
       [ 4.1932228e-08,  6.3955114e-04, -1.5785043e-03,  5.8087419e-14,
         3.0015895e-10],
       [ 1.2751379e-34, -4.8570976e-01,  0.0000000e+00,  0.0000000e+00,
        -2.1683326e-12],
       [ 1.6324746e-18,  1.1887324e+02, -1.4812396e+02, -2.5376248e+20,
         2.8604221e-37]], dtype=float32)>

### Matriks Multiplication

In [51]:
tf.matmul(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-31.914345, -35.661415, -37.309895, -45.12207 , -50.41586 ],
       [-66.75552 , -71.83186 , -77.155136, -83.56189 , -88.74093 ],
       [ 60.96257 ,  65.1554  ,  69.28105 ,  81.94736 ,  89.25382 ],
       [-54.90513 , -59.702946, -64.55476 , -71.779205, -78.73932 ],
       [-69.514946, -79.029106, -80.58886 , -90.03029 , -87.031494]],
      dtype=float32)>

### Nilai maksimal dari random_tensor dengan menggunakan axis 0 dan 1

In [91]:
tf.argmax(random_tensor, axis = 0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([4, 4, 0, 2, 2], dtype=int64)>

In [90]:
tf.argmax(random_tensor, axis = 1)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 0, 1, 0, 1], dtype=int64)>

### Nilai minimal dari random_tensor dengan menggunakan axis 0 dan 1

In [88]:
tf.argmin(random_tensor, axis = 0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([3, 0, 4, 4, 1], dtype=int64)>

In [89]:
tf.argmin(random_tensor, axis = 1)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 4, 2, 1, 3], dtype=int64)>

### Penggabungan antara variabel random_tensor dan prime_tensor menggunakan tf.concat

In [94]:
gabung1 = tf.concat([random_tensor, prime_tensor], axis = 0)
print(gabung1.shape)
print(gabung1)

(10, 5)
tf.Tensor(
[[  0.26088262  -1.1665442    0.55400825  -0.27793553  -0.24955325]
 [  0.581209    -0.6680276   -0.14766154   0.20139614  -0.8269629 ]
 [  0.5781196    0.8197328   -0.8544065    0.49225253   0.6271775 ]
 [  0.22934127  -0.9878349    0.12698117   0.15517129  -0.69218296]
 [  0.5954512    1.0592562   -1.0577646   -1.623136     0.43469283]
 [  2.           3.           5.           7.          11.        ]
 [ 13.          17.          19.          23.          29.        ]
 [ 31.          37.          41.          43.          47.        ]
 [ 53.          59.          61.          71.          73.        ]
 [ 79.          83.          89.          97.         101.        ]], shape=(10, 5), dtype=float32)


### Penggabungan antara variabel random_tensor dan prime_tensor menggunakan tf.stack

In [93]:
gabung2 = tf.stack([random_tensor, prime_tensor], axis = 0)
print(gabung2.shape)
print(gabung2)

(2, 5, 5)
tf.Tensor(
[[[  0.26088262  -1.1665442    0.55400825  -0.27793553  -0.24955325]
  [  0.581209    -0.6680276   -0.14766154   0.20139614  -0.8269629 ]
  [  0.5781196    0.8197328   -0.8544065    0.49225253   0.6271775 ]
  [  0.22934127  -0.9878349    0.12698117   0.15517129  -0.69218296]
  [  0.5954512    1.0592562   -1.0577646   -1.623136     0.43469283]]

 [[  2.           3.           5.           7.          11.        ]
  [ 13.          17.          19.          23.          29.        ]
  [ 31.          37.          41.          43.          47.        ]
  [ 53.          59.          61.          71.          73.        ]
  [ 79.          83.          89.          97.         101.        ]]], shape=(2, 5, 5), dtype=float32)


### Sorting

In [95]:
tf.sort(gabung1, direction="DESCENDING")

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[  0.55400825,   0.26088262,  -0.24955325,  -0.27793553,
         -1.1665442 ],
       [  0.581209  ,   0.20139614,  -0.14766154,  -0.6680276 ,
         -0.8269629 ],
       [  0.8197328 ,   0.6271775 ,   0.5781196 ,   0.49225253,
         -0.8544065 ],
       [  0.22934127,   0.15517129,   0.12698117,  -0.69218296,
         -0.9878349 ],
       [  1.0592562 ,   0.5954512 ,   0.43469283,  -1.0577646 ,
         -1.623136  ],
       [ 11.        ,   7.        ,   5.        ,   3.        ,
          2.        ],
       [ 29.        ,  23.        ,  19.        ,  17.        ,
         13.        ],
       [ 47.        ,  43.        ,  41.        ,  37.        ,
         31.        ],
       [ 73.        ,  71.        ,  61.        ,  59.        ,
         53.        ],
       [101.        ,  97.        ,  89.        ,  83.        ,
         79.        ]], dtype=float32)>

In [96]:
tf.argsort(gabung1, direction="DESCENDING")

<tf.Tensor: shape=(10, 5), dtype=int32, numpy=
array([[2, 0, 4, 3, 1],
       [0, 3, 2, 1, 4],
       [1, 4, 0, 3, 2],
       [0, 3, 2, 4, 1],
       [1, 0, 4, 2, 3],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0]])>

In [97]:
tf.sort(gabung2, direction="DESCENDING")

<tf.Tensor: shape=(2, 5, 5), dtype=float32, numpy=
array([[[  0.55400825,   0.26088262,  -0.24955325,  -0.27793553,
          -1.1665442 ],
        [  0.581209  ,   0.20139614,  -0.14766154,  -0.6680276 ,
          -0.8269629 ],
        [  0.8197328 ,   0.6271775 ,   0.5781196 ,   0.49225253,
          -0.8544065 ],
        [  0.22934127,   0.15517129,   0.12698117,  -0.69218296,
          -0.9878349 ],
        [  1.0592562 ,   0.5954512 ,   0.43469283,  -1.0577646 ,
          -1.623136  ]],

       [[ 11.        ,   7.        ,   5.        ,   3.        ,
           2.        ],
        [ 29.        ,  23.        ,  19.        ,  17.        ,
          13.        ],
        [ 47.        ,  43.        ,  41.        ,  37.        ,
          31.        ],
        [ 73.        ,  71.        ,  61.        ,  59.        ,
          53.        ],
        [101.        ,  97.        ,  89.        ,  83.        ,
          79.        ]]], dtype=float32)>

In [98]:
tf.argsort(gabung2, direction="DESCENDING")

<tf.Tensor: shape=(2, 5, 5), dtype=int32, numpy=
array([[[2, 0, 4, 3, 1],
        [0, 3, 2, 1, 4],
        [1, 4, 0, 3, 2],
        [0, 3, 2, 4, 1],
        [1, 0, 4, 2, 3]],

       [[4, 3, 2, 1, 0],
        [4, 3, 2, 1, 0],
        [4, 3, 2, 1, 0],
        [4, 3, 2, 1, 0],
        [4, 3, 2, 1, 0]]])>